<?php

namespace Database\Seeders;

use Bpuig\Subby\Models\Plan;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class PlanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //UNT START
        $plan_raw = [[
            'tag'=>"free",
            'name'=>"Free Plan",
            'description'=>"Free Plan",
            'is_active'=>true,
            'price'=>0,
            'signup_fee'=>0,
            'currency'=>"KZT",
            'trial_period'=>0,
            'trial_interval'=>"hour",
            'trial_mode'=>"outside",
            'grace_period'=>0,
            'grace_interval'=>"hour",
            'invoice_period'=>12,
            'invoice_interval'=>"month",
        ],
        [
            'tag'=>"basic",
            'name'=>"Basic Plan",
            'description'=>"Basic Plan for 1 month",
            'is_active'=>true,
            'price'=>1990,
            'signup_fee'=>0,
            'currency'=>"KZT",
            'trial_period'=>0,
            'trial_interval'=>"hour",
            'trial_mode'=>"outside",
            'grace_period'=>0,
            'grace_interval'=>"hour",
            'invoice_period'=>1,
            'invoice_interval'=>"month",
        ],
        [
            'tag'=>"standart",
            'name'=>"Standart Plan",
            'description'=>"Standart Plan for 3 months",
            'is_active'=>true,
            'price'=>3990,
            'signup_fee'=>0,
            'currency'=>"KZT",
            'trial_period'=>0,
            'trial_interval'=>"hour",
            'trial_mode'=>"outside",
            'grace_period'=>0,
            'grace_interval'=>"hour",
            'invoice_period'=>3,
            'invoice_interval'=>"month",
        ],
        [
            'tag'=>"pro",
            'name'=>"Pro Plan",
            'description'=>"Pro Plan for 6 months",
            'is_active'=>true,
            'price'=>6990,
            'signup_fee'=>0,
            'currency'=>"KZT",
            'trial_period'=>0,
            'trial_interval'=>"hour",
            'trial_mode'=>"outside",
            'grace_period'=>0,
            'grace_interval'=>"hour",
            'invoice_period'=>6,
            'invoice_interval'=>"month",
        ],
        [
            'tag'=>"premium",
            'name'=>"Premium Plan",
            'description'=>"Premium Plan for 12 months",
            'is_active'=>true,
            'price'=>12990,
            'signup_fee'=>0,
            'currency'=>"KZT",
            'trial_period'=>0,
            'trial_interval'=>"hour",
            'trial_mode'=>"outside",
            'grace_period'=>0,
            'grace_interval'=>"hour",
            'invoice_period'=>12,
            'invoice_interval'=>"month",
        ],
        //UNT ENDS

        //CONTENT START
        [
            'tag'=>"1",
            'name'=>"Математикалық сауаттылық/Математическая грамотность",
            'description'=>"Математикалық сауаттылық/Математическая грамотность",
            'is_active'=>true,
            'price'=>5000,
            'signup_fee'=>0,
            'currency'=>"KZT",
            'trial_period'=>0,
            'trial_interval'=>"hour",
            'trial_mode'=>"outside",
            'grace_period'=>0,
            'grace_interval'=>"hour",
            'invoice_period'=>1,
            'invoice_interval'=>"month",
        ],
       [
            'tag'=>"2",
            'name'=>"Қазақстан тарихы/История Казахстана",
            'description'=>"Қазақстан тарихы/История Казахстана",
            'is_active'=>true,
            'price'=>5000,
            'signup_fee'=>0,
            'currency'=>"KZT",
            'trial_period'=>0,
            'trial_interval'=>"hour",
            'trial_mode'=>"outside",
            'grace_period'=>0,
            'grace_interval'=>"hour",
            'invoice_period'=>1,
            'invoice_interval'=>"month",
        ],
        [
            'tag'=>"3",
            'name'=>"Оқу сауаттылығы/Грамотность чтения",
            'description'=>"Оқу сауаттылығы/Грамотность чтения",
            'is_active'=>true,
            'price'=>5000,
            'signup_fee'=>0,
            'currency'=>"KZT",
            'trial_period'=>0,
            'trial_interval'=>"hour",
            'trial_mode'=>"outside",
            'grace_period'=>0,
            'grace_interval'=>"hour",
            'invoice_period'=>1,
            'invoice_interval'=>"month",
        ],
        [
            'tag'=>"4",
            'name'=>"Математика/Математика",
            'description'=>"Математика/Математика",
            'is_active'=>true,
            'price'=>5000,
            'signup_fee'=>0,
            'currency'=>"KZT",
            'trial_period'=>0,
            'trial_interval'=>"hour",
            'trial_mode'=>"outside",
            'grace_period'=>0,
            'grace_interval'=>"hour",
            'invoice_period'=>1,
            'invoice_interval'=>"month",
        ],
        [
            'tag'=>"5",
            'name'=>"Физика/Физика",
            'description'=>"Физика/Физика",
            'is_active'=>true,
            'price'=>5000,
            'signup_fee'=>0,
            'currency'=>"KZT",
            'trial_period'=>0,
            'trial_interval'=>"hour",
            'trial_mode'=>"outside",
            'grace_period'=>0,
            'grace_interval'=>"hour",
            'invoice_period'=>1,
            'invoice_interval'=>"month",
        ],
        [
            'tag'=>"6",
            'name'=>"Химия/Химия",
            'description'=>"Химия/Химия",
            'is_active'=>true,
            'price'=>5000,
            'signup_fee'=>0,
            'currency'=>"KZT",
            'trial_period'=>0,
            'trial_interval'=>"hour",
            'trial_mode'=>"outside",
            'grace_period'=>0,
            'grace_interval'=>"hour",
            'invoice_period'=>1,
            'invoice_interval'=>"month",
        ],
        [
            'tag'=>"7",
            'name'=>"Биология/Биология",
            'description'=>"Биология/Биология",
            'is_active'=>true,
            'price'=>5000,
            'signup_fee'=>0,
            'currency'=>"KZT",
            'trial_period'=>0,
            'trial_interval'=>"hour",
            'trial_mode'=>"outside",
            'grace_period'=>0,
            'grace_interval'=>"hour",
            'invoice_period'=>1,
            'invoice_interval'=>"month",
        ],
        [
            'tag'=>"8",
            'name'=>"География/География",
            'description'=>"География/География",
            'is_active'=>true,
            'price'=>5000,
            'signup_fee'=>0,
            'currency'=>"KZT",
            'trial_period'=>0,
            'trial_interval'=>"hour",
            'trial_mode'=>"outside",
            'grace_period'=>0,
            'grace_interval'=>"hour",
            'invoice_period'=>1,
            'invoice_interval'=>"month",
        ],
        [
            'tag'=>"9",
            'name'=>"Дүниежүзі тарихы/Всемирная история",
            'description'=>"Дүниежүзі тарихы/Всемирная история",
            'is_active'=>true,
            'price'=>5000,
            'signup_fee'=>0,
            'currency'=>"KZT",
            'trial_period'=>0,
            'trial_interval'=>"hour",
            'trial_mode'=>"outside",
            'grace_period'=>0,
            'grace_interval'=>"hour",
            'invoice_period'=>1,
            'invoice_interval'=>"month",
        ],
        [
            'tag'=>"10",
            'name'=>"Құқық/Основы права",
            'description'=>"Құқық/Основы права",
            'is_active'=>true,
            'price'=>5000,
            'signup_fee'=>0,
            'currency'=>"KZT",
            'trial_period'=>0,
            'trial_interval'=>"hour",
            'trial_mode'=>"outside",
            'grace_period'=>0,
            'grace_interval'=>"hour",
            'invoice_period'=>1,
            'invoice_interval'=>"month",
        ],
        [
            'tag'=>"11",
            'name'=>"Ағылшын тілі/Английский язык",
            'description'=>"Ағылшын тілі/Английский язык",
            'is_active'=>true,
            'price'=>5000,
            'signup_fee'=>0,
            'currency'=>"KZT",
            'trial_period'=>0,
            'trial_interval'=>"hour",
            'trial_mode'=>"outside",
            'grace_period'=>0,
            'grace_interval'=>"hour",
            'invoice_period'=>1,
            'invoice_interval'=>"month",
        ],
        [
            'tag'=>"12",
            'name'=>"Қазақ тілі/Казахский язык",
            'description'=>"Қазақ тілі/Казахский язык",
            'is_active'=>true,
            'price'=>5000,
            'signup_fee'=>0,
            'currency'=>"KZT",
            'trial_period'=>0,
            'trial_interval'=>"hour",
            'trial_mode'=>"outside",
            'grace_period'=>0,
            'grace_interval'=>"hour",
            'invoice_period'=>1,
            'invoice_interval'=>"month",
        ],
        [
            'tag'=>"13",
            'name'=>"Қазақ әдебиеті/Казахская литература",
            'description'=>"Қазақ әдебиеті/Казахская литература",
            'is_active'=>true,
            'price'=>5000,
            'signup_fee'=>0,
            'currency'=>"KZT",
            'trial_period'=>0,
            'trial_interval'=>"hour",
            'trial_mode'=>"outside",
            'grace_period'=>0,
            'grace_interval'=>"hour",
            'invoice_period'=>1,
            'invoice_interval'=>"month",
        ],
        [
            'tag'=>"14",
            'name'=>"Орыс тілі/Русский язык",
            'description'=>"Орыс тілі/Русский язык",
            'is_active'=>true,
            'price'=>5000,
            'signup_fee'=>0,
            'currency'=>"KZT",
            'trial_period'=>0,
            'trial_interval'=>"hour",
            'trial_mode'=>"outside",
            'grace_period'=>0,
            'grace_interval'=>"hour",
            'invoice_period'=>1,
            'invoice_interval'=>"month",
        ],
        [
            'tag'=>"15",
            'name'=>"Орыс әдебиеті/Русская литература",
            'description'=>"Орыс әдебиеті/Русская литература",
            'is_active'=>true,
            'price'=>5000,
            'signup_fee'=>0,
            'currency'=>"KZT",
            'trial_period'=>0,
            'trial_interval'=>"hour",
            'trial_mode'=>"outside",
            'grace_period'=>0,
            'grace_interval'=>"hour",
            'invoice_period'=>1,
            'invoice_interval'=>"month",
        ],
        [
            'tag'=>"16",
            'name'=>"Информатика/Информатика",
            'description'=>"Информатика/Информатика",
            'is_active'=>true,
            'price'=>5000,
            'signup_fee'=>0,
            'currency'=>"KZT",
            'trial_period'=>0,
            'trial_interval'=>"hour",
            'trial_mode'=>"outside",
            'grace_period'=>0,
            'grace_interval'=>"hour",
            'invoice_period'=>1,
            'invoice_interval'=>"month",
        ]];
        //CONTENT END

        foreach ($plan_raw as $value){
            if(!Plan::whereTag($value["tag"])->exists()){
                Plan::create($value);
            }
        }
    }
}
